### ISSUE TITLE
Update Links and App msgs

### ISSUE THREAD

**Issue by heyoka404** [we-commit/in-dex-explorer#3]
Offline msg: "Trojan is currently under maintenance-- It'll be back shortly." 

Discord invite:
Trojan is part of the Offshore DAO 🏝
Jump in:
[Discord] 
https://discord.com/invite/offshore

Footer Links:
Discord: https://discord.com/invite/offshore
Twitter: 
https://twitter.com/offshoredao
Medium: Remove
Github: https://github.com/we-commit

**Comment by 1devNdogs** [comment]
#5

**Comment by heyoka404** [comment]
rdy.
